### ISSUE TITLE
[Feature][Question] Add builtin_standard for the `minetest` lua api

### ISSUE THREAD

**Issue by BuckarooBanzay** [lunarmodules/luacheck#107]
I'd like to add a builtin_standard for the `minetest` lua api (see: https://github.com/minetest/minetest/blob/master/doc/lua_api.md)

Similar to: https://github.com/lunarmodules/luacheck/blob/master/src/luacheck/builtin_standards/love.lua

Give me a :+1: and i open a PR for it.

**Comment by alerque** [comment]
Sure, this sounds reasonable.

The only catch will be that after you get a PR working to your satisfaction I'll want to see some testing. Since I don't have any involvement in minetest, one other party that actually uses minetest and can verify your PR would be useful, and/or you can setup CI checks on public code somewhere using GH actions so we can see it in action.
